title: APU-SCHOOL
description: 愛知県立大学の学生による学習支援ボランティア団体 APU-SCHOOL の公式サイト
url: "https://a-p-u-school.github.io"
baseurl: "/APUSchool.github.io"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
